pipeline {
  // agent any
  // agent { docker { image 'maven:latest' } }
  agent { //here we select only docker build agents
	docker {
	  image 'maven:latest' //container will start from this image
	}
  }
  stages {
	stage('Build') {
	  steps {
	    sh "mvn --version"
		echo "Build"
	  }
	}
	stage('Test') {
	  steps {
		echo "Test"
	  }
	}
	stage('Integration Test') {
	  steps {
		echo "Integration Test"
	  }
	}
  }
  post {
    always {
      echo "Post/always block - executed always."
	}
    success {
      echo "Post/success block - executed on success."
	}
    failure {
      echo "Post/failure block - executed on failure."
	}
  }
}
