pipeline {
  agent any
  environment {
    //dockerHome = tool 'myDocker'
	mavenHome = tool 'myMaven'
	//PATH = "$dockerHome/bin:$mavenHome/bin:$PATH"
	PATH = "$mavenHome/bin:$PATH"
  }
  stages {
	stage('Build') {
	  steps {
		//sh 'docker version'
		bash 'mvn -version' 
		echo "Build"
	  }
	}
	stage('Test') {
	  steps {
		echo "Test"
	  }
	}
	stage('Integration Test') {
	  steps {
		echo "Integration Test"
	  }
	}
  }
  post {
    always {
      echo "Post/always block - executed always."
	}
    success {
      echo "Post/success block - executed on success."
	}
    failure {
      echo "Post/failure block - executed on failure."
	}
  }
}
