pipeline {
  agent any
  stages {
	stage('Build') {
	  steps {
		echo "Build"
	  }
	}
	stage('Test') {
	  steps {
		echo "Test"
	  }
	}
	stage('Integration Test') {
	  steps {
		echo "Integration Test"
	  }
	}
  }
  post {
    always {
      echo "Post/always block - executed always."
	}
    success {
      echo "Post/success block - executed on success."
	}
    failure {
      echo "Post/failure block - executed on failure."
	}
  }
}
